import { Product, Category, AppConfig } from '@/types';

export const defaultConfig: AppConfig = {
  business: {
    name: "DeliFoods",
    logo: "/logo.svg",
    description: "Los mejores sabores para tu hogar, preparados con amor y ingredientes frescos.",
    phone: "+51 906 684 284",
    whatsapp: "+51 906 684 284",
    email: "info@delifoods.com",
    address: "Santa paula 470",
    hours: "Lunes a Domingo: 7:00 PM - 11:00 PM",
    socialMedia: {
      facebook: "https://facebook.com/delifoods",
      instagram: "https://instagram.com/delifoods",
    }
  },
  delivery: {
    enabled: true,
    zones: [
      { id: "1", name: "Pando Tercera Etapa", cost: 5, description: "Entrega en 30-45 min" },
      { id: "2", name: "Palomino", cost: 5, description: "Entrega en 45-60 min" },
      { id: "3", name: "Santa Emma", cost: 5, description: "Entrega en 45-60 min" },
    ],
    estimatedTime: "30-60 minutos"
  },
  theme: {
    primaryColor: "#22C55E",
    secondaryColor: "#F97316",
    accentColor: "#3B82F6",
    backgroundPattern: "subtle-prism"
  }
};

export const defaultCategories: Category[] = [
  { id: "1", name: "Hamburguesas", icon: "🍔", active: true, order: 1 },
  { id: "2", name: "BBQ", icon: "🍕", active: true, order: 2 },
  { id: "3", name: "Combos", icon: "🍽️", active: true, order: 3 },
  { id: "4", name: "Bebidas", icon: "🥤", active: true, order: 4 },
  { id: "5", name: "Al Plato", icon: "🍽️", active: true, order: 5 },
  { id: "6", name: "Ensaladas", icon: "🥗", active: true, order: 6 },
  { id: "7", name: "Broaster", icon: "🍗", active: true, order: 7 },
];

export const defaultProducts: Product[] = [
  {
    id: "1",
    name: "Hamburguesa Clásica",
    price: 18,
    image: "/imagen/hamburguesa_clasica.webp",
    description: " Carne de res, lechuga, tomate, queso cheddar y salsa.",
    category: "1",
    available: true,
    featured: true,
  },
  {
    id: "2",
    name: "Salchipapa Royal",
    price: 11,
    image: "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Salchipapa royal 400 gramos (hot dog, huevo, queso)",
    category: "5",
    available: true,
    featured: true,
  },
  {
    id: "3",
    name: "Combo Familiar",
    price: 55,
    image: "https://images.pexels.com/photos/1099680/pexels-photo-1099680.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "2 hamburguesas + papas grandes + 2 bebidas + postre para compartir.",
    category: "3",
    available: true,
    featured: true,
  },
  {
    id: "4",
    name: "Concordia o Fanta 1/2 litro",
    price: 3,
    image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Concordia o Fanta 1/2 litro",
    category: "4",
    available: true,
  },
  {
    id: "5",
    name: "Salchipapa Clásica",
    price: 9,
    image: "/imagen/salchipapa_clasica.webp",
    description: "Salchipapa clásica 400 gramos",
    category: "5",
    available: true,
  },
  {
    id: "6",
    name: "Ensalada César",
    price: 18,
    image: "https://images.pexels.com/photos/1213710/pexels-photo-1213710.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Lechuga romana, crutones, queso parmesano y aderezo césar casero.",
    category: "6",
    available: true,
  },
  {
    id: "7",
    name: "Hamburguesa BBQ",
    price: 20,
    image: "https://images.pexels.com/photos/1556909/pexels-photo-1556909.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Hamburguesa con salsa BBQ, y queso cheddar.",
    category: "1",
    available: true,
  },
  {
    id: "8",
    name: "Salchipapa Bravaza",
    price: 13,
    image: "/imagen/salchipapa_brabaza.webp",
    description: "Salchipapa bravaza 400 gramos (hoy dog, huevo, jamon y tocino)",
    category: "5",
    available: true,
  },
  {
    id: "9",
    name: "Alita Broaster",
    price: 10,
    image: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Pizza con pepperoni, mozzarella y salsa de tomate especial.",
    category: "7",
    available: true,
  },
  {
    id: "10",
    name: "Pierna Broaster",
    price: 11,
    image: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Pizza con pepperoni, mozzarella y salsa de tomate especial.",
    category: "7",
    available: true,
  },
  {
    id: "11",
    name: "Muslo Broaster",
    price: 12,
    image: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Pizza con pepperoni, mozzarella y salsa de tomate especial.",
    category: "7",
    available: true,
  },
  {
    id: "12",
    name: "Pecho Broaster",
    price: 13,
    image: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Pizza con pepperoni, mozzarella y salsa de tomate especial.",
    category: "7",
    available: true,
  },
  {
    id: "13",
    name: "Alitas BBQ",
    price: 14,
    image: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Alitas BBQ (papas fritas + Ensalada)",
    category: "2",
    available: true,
  },
  {
    id: "14",
    name: "Deditos BBQ",
    price: 14,
    image: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Deditos BBQ (papas fritas + Ensalada)",
    category: "2",
    available: true,
  },
  {
    id: "15",
    name: "Alitas Cevicheras",
    price: 15,
    image: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Alitas Cevicheras",
    category: "2",
    available: true,
  },
  {
    id: "16",
    name: "Alitas en salsa de maracuya",
    price: 14,
    image: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Alitas en salsa de maracuya",
    category: "2",
    available: true,
  },
  {
    id: "17",
    name: "Chicha 1/2 litro",
    price: 4,
    image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Chicha de 1/2 litro",
    category: "4",
    available: true,
  },
  {
    id: "18",
    name: "Maracuya 1/2 litro",
    price: 4,
    image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Maracuya 1/2 litro",
    category: "4",
    available: true,
  },
  {
    id: "19",
    name: "Chicha 1 litro",
    price: 8,
    image: "https://images.pexels.com/photos/28490837/pexels-photo-28490837.jpeg",
    description: "Chicha 1 litro",
    category: "4",
    available: true,
  },
  {
    id: "20",
    name: "Maracuya 1 Litro",
    price: 8,
    image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Maracuya 1 litro",
    category: "4",
    available: true,
  },
  {
    id: "21",
    name: "Papaya 1/2 litro",
    price: 7,
    image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Papaya 1/2 litro",
    category: "4",
    available: true,
  },
  {
    id: "22",
    name: "Piña 1/2 litro",
    price: 7,
    image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Papaya 1 litro",
    category: "4",
    available: true,
  },
  {
    id: "23",
    name: "Fresa con Leche 1/2 litro",
    price: 10,
    image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Fresa con Leche 1/2 litro",
    category: "4",
    available: true,
  },
  {
    id: "24",
    name: "Lucuma con Leche 1/2 litro",
    price: 10,
    image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Lucuma con Leche 1/2 litro",
    category: "4",
    available: true,
  },
  {
    id: "25",
    name: "Inka cola 1/2 litro",
    price: 3.50,
    image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Inka cola 1/2 litro",
    category: "4",
    available: true,
  },
  {
    id: "26",
    name: "Coca Cola 1/2 litro",
    price: 3.50,
    image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Coca Cola 1/2 litro",
    category: "4",
    available: true,
  },
  {
    id: "27",
    name: "Salchipapa Clásica",
    price: 9,
    image: "https://images.pexels.com/photos/461431/pexels-photo-461431.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Salchipapa clásica 400 gramos",
    category: "5",
    available: true,
  },
  {
    id: "28",
    name: "Filete de Pechuga Jaxu",
    price: 14,
    image: "https://images.pexels.com/photos/461431/pexels-photo-461431.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Filete de pechuga jaxu",
    category: "5",
    available: true,
  }, 
  {
    id: "29",
    name: "Salchipapa Tragona",
    price: 15,
    image: "https://images.pexels.com/photos/461431/pexels-photo-461431.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "Salchipapa clásica 400 gramos (hot dog, carne, queso, jamon, huevo y tocino)",
    category: "5",
    available: true,
  }, 
  {
    id: "30",
    name: "SalchiCrispy",
    price: 14,
    image: "https://images.pexels.com/photos/461431/pexels-photo-461431.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=2",
    description: "salchipapa crispy 400 gramos",
    category: "5",
    available: true,
  }, 
];